package:
  name: meggie
  version: "0.17.1"

source:
  path: .

app:
  entry: meggie
  summary: User-friendly graphical interface to do M/EEG analysis
  type: desk

requirements:
  build:
    - python
    - setuptools
    - mne >=0.22.0

  run:
    - python
    - mne >=0.22.0
    - pyqt >=5.0.0
    - xlwt
    - xlrd
    - mayavi
    - h5py
    - joblib
    - scikit-learn
    - pysurfer
    - h5py

about:
  license: BSD (3-clause)
  summary: 'MNE graphical user interface for MEG and EEG data analysis.'
