package:
  name: meggie
  version: "0.9.0"

source:
  path: .

requirements:
  build:
    - python
    - setuptools
    - mne ==0.17.0

  run:
    - python
    - pyqt >=5.0.0
    - xlwt
    - xlrd
    - mayavi
    - h5py
    - joblib
    - scikit-learn
    - pysurfer
    - h5py
    - mne ==0.17.0

about:
  license: BSD (3-clause)
  summary: 'MNE graphical user interface for MEG and EEG data analysis.'
