package:
  name: meggie
  version: "0.9.1"

source:
  path: .

requirements:
  build:
    - python >=3.0.0
    - setuptools
    - mne ==0.17.0

  run:
    - python >=3.0.0
    - mne ==0.17.0
    - pyqt >=5.0.0
    - xlwt
    - xlrd
    - mayavi
    - h5py
    - joblib
    - scikit-learn
    - pysurfer
    - h5py

about:
  license: BSD (3-clause)
  summary: 'MNE graphical user interface for MEG and EEG data analysis.'
