package:
  name: meggie
  version: "0.8.0"

source:
  path: .

requirements:
  build:
    - python
    - setuptools
    - mne ==0.15.2

  run:
    - python
    - pyqt ==4.11.4
    - xlwt
    - xlrd
    - mayavi
    - h5py
    - joblib
    - scikit-learn
    - pysurfer
    - h5py
    - mne ==0.15.2

about:
  license: BSD (3-clause)
  summary: 'MNE graphical user interface for MEG and EEG data analysis.'
